version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "🏗️ Building Next.js..."
      - npm run build
      - echo "📦 Exporting static files to out/..."
      - npm run export

artifacts:
  files:
    - '**/*'
  base-directory: out
